# Generated by Django 5.2.6 on 2025-09-16 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereço', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endreço')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cep')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='image_Clients', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Marca')),
                ('logo', models.ImageField(blank=True, upload_to='image_fabricante', verbose_name='Marca')),
                ('site', models.CharField(max_length=200, verbose_name='site')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('ano', models.IntegerField(default=2025, verbose_name='Ano')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor')),
                ('placa', models.CharField(max_length=8, verbose_name='Placa')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='image_veiculo', verbose_name='foto')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('id_fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fabricante')),
            ],
        ),
    ]
